
broker:
  ip: "127.0.0.1"
  tcpport: "4222"
  httpport: "8222"
  user: "alfxnats"
  pwd: "alfxnats"
  clusterid: "alfxnats"
database:
  ip: "110.1.1.227"
  port: "27017"
  user: "alfxdev"
  pwd: "alfxdev"
  dbname: "alfxdev"
scheduler:
  a2rparallel: 4
  sleeptime: 300
worker:
  name: "worker1"
  domains:
    officenet: 3
    producnet: 3
    free: 3
  temppath: "/home/alfx/proc"
common:
  filepath: "/home/alfx/file"
  logpath: "home/alfx/log"
  logdebug: true
  logtrace: true
report:
  localip: "127.0.0.1"
  localport: ""












